
services:
  aceest-app:
    build: .
    container_name: aceest-app
    ports:
      - "5900:5900"
      - "6080:6080"
    environment:
      - DISPLAY=:99
    volumes:
      - .:/app
    mem_limit: 512m